apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    env: dev
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django-app-pod
      labels:
        env: dev
        app: django
    spec:
      containers:
        - name: django-app
          image: anneg8/django_app:latest
          ports:
            - containerPort: 80
          env:
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: 45.9.42.54,192.168.59.104,127.0.0.1,localhost
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: media-volume
              mountPath: /media
      volumes:
        - name: media-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels:
    env: dev
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234
