apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  namespace:
  labels:
    env: dev
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django-app-pod
      labels:
        env: dev
        app: django
    spec:
      containers:
        - name: django-app
          image: anneg8/django_app:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-secret
            - configMapRef:
                name: django-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
          volumeMounts:
            - name: media-volume
              mountPath: /media
            - name: pg-cert-volume
              mountPath: /root/.postgresql/root.crt
              subPath: root.crt
              readOnly: true
      volumes:
        - name: media-volume
          emptyDir: {}
        - name: pg-cert-volume
          secret:
            secretName: pg-root-cert
