apiVersion: v1
kind: Secret
metadata:
  name: django-superuser-secret
  namespace:
type: Opaque
stringData:
  DJANGO_SUPERUSER_USERNAME: ""
  DJANGO_SUPERUSER_EMAIL: ""
  DJANGO_SUPERUSER_PASSWORD: ""
