apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-anna-veselova
  labels:
    app: nginx
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
