apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    env: dev
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django-app-pod
      labels:
        env: dev
        app: django
    spec:
      containers:
        - name: django-app
          image: anneg8/django_app:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: media-volume
              mountPath: /media
      volumes:
        - name: media-volume
          emptyDir: {}
