apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cronjob
  labels:
    env: dev
    app: service
spec:
  schedule: "0 2 * * *"
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: django-clearsessions
              image: anneg8/django_app:latest
              command: [ "python", "manage.py", "clearsessions" ]
              envFrom:
                - secretRef:
                    name: django-secret
