apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-migrate
          image: anneg8/django_app:latest
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: django-secret
