apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: CHANGE_ME
  DATABASE_URL: postgres://username:userpassword@postgres-db-postgresql:5432/dbname
  DEBUG: "False"
  ALLOWED_HOSTS: "star-burger.test"
